---
name: Release

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
      release-git-tag: ${{ steps.release.outputs.release-git-tag }}
    steps:
    - uses: actions/checkout@v4

    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2.2.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: release
    name: Build and Push Docker Images
    strategy:
      matrix:
        os: [{package_type: deb, os: ubuntu, version: 22.04}, {package_type: deb, os: debian, version: 12-slim}, {package_type: apk, os: alpine, version: 3}, {package_type: rpm, os: amazonlinux, version: 2023}]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Set release tag
      id: set-tag
      run: |
        if [ -n "${{ needs.release.outputs.release-git-tag }}" ]; then
          echo "RELEASE_TAG=${{ needs.release.outputs.release-git-tag }}" >> $GITHUB_ENV
        else
          echo "RELEASE_TAG=unreleased" >> $GITHUB_ENV
        fi

    - name: Extract versions and SHAs from .env
      run: |
        export $(grep -v '^#' .env | xargs) && \
        echo "KONG_VERSION=${KONG_VERSION}" >> $GITHUB_ENV && \
        echo "KONG_SHA=${KONG_SHA}" >> $GITHUB_ENV && \
        echo "OPENRESTY_VERSION=${OPENRESTY_VERSION}" >> $GITHUB_ENV && \
        echo "LUAROCKS_VERSION=${LUAROCKS_VERSION}" >> $GITHUB_ENV && \
        echo "PCRE_VERSION=${PCRE_VERSION}" >> $GITHUB_ENV >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/gh-org-template/kong-docker
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=${{ env.RELEASE_TAG }}
          type=raw,value=${{ env.KONG_VERSION }}
        flavor: |
          suffix=-${{ matrix.os.os }}
        labels: |
          org.opencontainers.image.version=${{ env.RELEASE_TAG }}
          org.opencontainers.image.revision=${{ env.KONG_SHA }}
          org.opencontainers.image.openresty.version=${{ env.OPENRESTY_VERSION }}
          org.opencontainers.image.luarocks.version=${{ env.LUAROCKS_VERSION }}
          org.opencontainers.image.pcre.version=${{ env.PCRE_VERSION }}
          org.opencontainers.image.kong.version=${{ env.KONG_VERSION }}

    - name: Log in to the Container registry
      if: ${{ needs.release.outputs.published == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ needs.release.outputs.published == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile.${{ matrix.os.package_type }}
        build-args: |
          DISTRIBUTION_OS=${{ matrix.os.os }}
          DISTRIBUTION_VERSION=${{ matrix.os.version }}

  done:
    needs: [release, build-and-push]
    name: Done
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      if: ${{ needs.release.outputs.published == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a final multi-arch manifest for Ubuntu only
      if: ${{ needs.release.outputs.published == 'true' }}
      run: |
        docker manifest create ghcr.io/gh-org-template/kong-docker:${{ needs.release.outputs.release-git-tag }} \
          ghcr.io/gh-org-template/kong-docker:${{ needs.release.outputs.release-git-tag }}-amd64-ubuntu \
          ghcr.io/gh-org-template/kong-docker:${{ needs.release.outputs.release-git-tag }}-arm64-ubuntu
        docker manifest push ghcr.io/gh-org-template/kong-docker:${{ needs.release.outputs.release-git-tag }}

    - name: Check for Failed Jobs
      run: |
        if [[ "${{ needs.release.result }}" == "failure" || "${{ needs.build-and-push.result }}" == "failure" || "${{ needs.multi-arch.result }}" == "failure" ]]; then
          echo "One or more jobs failed. Marking release as failed."
          exit 1
        else
          echo "All jobs succeeded or were skipped. Marking release as successful."
        fi
    - run: echo 'done'
